apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my-django-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: messaging-app
            port:
              number: 8000
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: messaging-app
            port:
              number: 8000

